#Input Types
#Category Table Input
input CategoryInput {
  name: String!
}

# Comment Table Input
input CommentInput {
  userID: ID!
  relatedItemID: ID!
  relatedItemType: ContentType!
  datePosted: String!
  value: String!
  likes: Int!
}

# Notification Table Input
input NotificationInput {
  userID: ID!
  relatedItemID: ID!
  relatedItemType: ContentType!
  isRead: Boolean!
  dateCreated: String!
}

# Request Table Input
input RequestInput {
  categoryID: ID
  title: String!
  requestedBy: String!
  datePosted: String!
  brief: String
  desc: String
  postLenMin: Int
  postLenMax: Int!
  likes: Int!
}

# Requirement Table Input
input RequirementInput {
  requestID: ID!
  type: String!
  value: String!
}

# Scene Table Input
input SceneInput {
  requestID: ID!
  createdByID: ID!
  sceneURL: String!
  thumbnailURL: String!
  dateSubmitted: String!
  status: SceneStatus!
  duration: Int!
  resolution: String!
}

# Tag Table Input
input TagInput {
  name: String!
}

# Transaction Table Input
input TransactionInput {
  userID: ID!
  paidByID: ID!
  paidToID: ID!
  value: Int!
  paymentDate: String!
}

# User Table Input
input UserInput {
  username: String!
  email: String!
  password: String!
  profPicUrl: String
}

#enums
enum ContentType {
  Request,
  Scene,
  Account
}

enum SceneStatus {
  Pending,
  Approved,
  Rejected
}